/* 國碼清單（E.164）：忘記密碼頁「選擇國家」下拉專用。
   台灣／中國／香港／澳門釘在最前面（PINNED，順序固定），
   其餘依中文名稱排序（優先用「筆畫」排序 locale，瀏覽器不支援時自動退回預設中文排序）。
   目前收錄約 200 個主權國家，未逐一收錄海外屬地／特殊行政區（如英屬維京群島），
   之後若有使用者反應找不到自己的國家，再個別補入即可。 */
var COUNTRY_CODES = (function () {
  var PINNED = [
    { iso: 'TW', name: '台灣',   dial: '886' },
    { iso: 'CN', name: '中國',   dial: '86'  },
    { iso: 'HK', name: '香港',   dial: '852' },
    { iso: 'MO', name: '澳門',   dial: '853' }
  ];

  var REST = [
    // 亞洲
    { iso: 'JP', name: '日本',     dial: '81'  },
    { iso: 'KR', name: '韓國',     dial: '82'  },
    { iso: 'KP', name: '北韓',     dial: '850' },
    { iso: 'MN', name: '蒙古',     dial: '976' },
    { iso: 'VN', name: '越南',     dial: '84'  },
    { iso: 'TH', name: '泰國',     dial: '66'  },
    { iso: 'KH', name: '柬埔寨',   dial: '855' },
    { iso: 'LA', name: '寮國',     dial: '856' },
    { iso: 'MM', name: '緬甸',     dial: '95'  },
    { iso: 'MY', name: '馬來西亞', dial: '60'  },
    { iso: 'SG', name: '新加坡',   dial: '65'  },
    { iso: 'ID', name: '印尼',     dial: '62'  },
    { iso: 'BN', name: '汶萊',     dial: '673' },
    { iso: 'PH', name: '菲律賓',   dial: '63'  },
    { iso: 'TL', name: '東帝汶',   dial: '670' },
    { iso: 'IN', name: '印度',     dial: '91'  },
    { iso: 'PK', name: '巴基斯坦', dial: '92'  },
    { iso: 'BD', name: '孟加拉',   dial: '880' },
    { iso: 'LK', name: '斯里蘭卡', dial: '94'  },
    { iso: 'NP', name: '尼泊爾',   dial: '977' },
    { iso: 'BT', name: '不丹',     dial: '975' },
    { iso: 'MV', name: '馬爾地夫', dial: '960' },
    { iso: 'AF', name: '阿富汗',   dial: '93'  },
    { iso: 'KZ', name: '哈薩克',   dial: '7'   },
    { iso: 'UZ', name: '烏茲別克', dial: '998' },
    { iso: 'TM', name: '土庫曼',   dial: '993' },
    { iso: 'TJ', name: '塔吉克',   dial: '992' },
    { iso: 'KG', name: '吉爾吉斯', dial: '996' },

    // 中東
    { iso: 'SA', name: '沙烏地阿拉伯',     dial: '966' },
    { iso: 'AE', name: '阿拉伯聯合大公國', dial: '971' },
    { iso: 'QA', name: '卡達',             dial: '974' },
    { iso: 'BH', name: '巴林',             dial: '973' },
    { iso: 'KW', name: '科威特',           dial: '965' },
    { iso: 'OM', name: '阿曼',             dial: '968' },
    { iso: 'YE', name: '葉門',             dial: '967' },
    { iso: 'IQ', name: '伊拉克',           dial: '964' },
    { iso: 'IR', name: '伊朗',             dial: '98'  },
    { iso: 'SY', name: '敘利亞',           dial: '963' },
    { iso: 'LB', name: '黎巴嫩',           dial: '961' },
    { iso: 'JO', name: '約旦',             dial: '962' },
    { iso: 'IL', name: '以色列',           dial: '972' },
    { iso: 'PS', name: '巴勒斯坦',         dial: '970' },
    { iso: 'TR', name: '土耳其',           dial: '90'  },
    { iso: 'CY', name: '賽普勒斯',         dial: '357' },
    { iso: 'GE', name: '喬治亞',           dial: '995' },
    { iso: 'AM', name: '亞美尼亞',         dial: '374' },
    { iso: 'AZ', name: '亞塞拜然',         dial: '994' },

    // 歐洲
    { iso: 'GB', name: '英國',     dial: '44'  },
    { iso: 'IE', name: '愛爾蘭',   dial: '353' },
    { iso: 'FR', name: '法國',     dial: '33'  },
    { iso: 'DE', name: '德國',     dial: '49'  },
    { iso: 'NL', name: '荷蘭',     dial: '31'  },
    { iso: 'BE', name: '比利時',   dial: '32'  },
    { iso: 'LU', name: '盧森堡',   dial: '352' },
    { iso: 'CH', name: '瑞士',     dial: '41'  },
    { iso: 'AT', name: '奧地利',   dial: '43'  },
    { iso: 'IT', name: '義大利',   dial: '39'  },
    { iso: 'ES', name: '西班牙',   dial: '34'  },
    { iso: 'PT', name: '葡萄牙',   dial: '351' },
    { iso: 'GR', name: '希臘',     dial: '30'  },
    { iso: 'PL', name: '波蘭',     dial: '48'  },
    { iso: 'CZ', name: '捷克',     dial: '420' },
    { iso: 'SK', name: '斯洛伐克', dial: '421' },
    { iso: 'HU', name: '匈牙利',   dial: '36'  },
    { iso: 'RO', name: '羅馬尼亞', dial: '40'  },
    { iso: 'BG', name: '保加利亞', dial: '359' },
    { iso: 'HR', name: '克羅埃西亞', dial: '385' },
    { iso: 'SI', name: '斯洛維尼亞', dial: '386' },
    { iso: 'RS', name: '塞爾維亞', dial: '381' },
    { iso: 'BA', name: '波士尼亞與赫塞哥維納', dial: '387' },
    { iso: 'ME', name: '蒙特內哥羅', dial: '382' },
    { iso: 'MK', name: '北馬其頓', dial: '389' },
    { iso: 'AL', name: '阿爾巴尼亞', dial: '355' },
    { iso: 'XK', name: '科索沃',   dial: '383' },
    { iso: 'DK', name: '丹麥',     dial: '45'  },
    { iso: 'SE', name: '瑞典',     dial: '46'  },
    { iso: 'NO', name: '挪威',     dial: '47'  },
    { iso: 'FI', name: '芬蘭',     dial: '358' },
    { iso: 'IS', name: '冰島',     dial: '354' },
    { iso: 'EE', name: '愛沙尼亞', dial: '372' },
    { iso: 'LV', name: '拉脫維亞', dial: '371' },
    { iso: 'LT', name: '立陶宛',   dial: '370' },
    { iso: 'RU', name: '俄羅斯',   dial: '7'   },
    { iso: 'UA', name: '烏克蘭',   dial: '380' },
    { iso: 'BY', name: '白俄羅斯', dial: '375' },
    { iso: 'MD', name: '摩爾多瓦', dial: '373' },
    { iso: 'MC', name: '摩納哥',   dial: '377' },
    { iso: 'LI', name: '列支敦斯登', dial: '423' },
    { iso: 'AD', name: '安道爾',   dial: '376' },
    { iso: 'SM', name: '聖馬利諾', dial: '378' },
    { iso: 'VA', name: '梵蒂岡',   dial: '379' },
    { iso: 'MT', name: '馬爾他',   dial: '356' },

    // 大洋洲
    { iso: 'AU', name: '澳洲',           dial: '61'  },
    { iso: 'NZ', name: '紐西蘭',         dial: '64'  },
    { iso: 'FJ', name: '斐濟',           dial: '679' },
    { iso: 'PG', name: '巴布亞紐幾內亞', dial: '675' },
    { iso: 'SB', name: '索羅門群島',     dial: '677' },
    { iso: 'VU', name: '萬那杜',         dial: '678' },
    { iso: 'WS', name: '薩摩亞',         dial: '685' },
    { iso: 'TO', name: '東加',           dial: '676' },
    { iso: 'KI', name: '吉里巴斯',       dial: '686' },
    { iso: 'NR', name: '諾魯',           dial: '674' },
    { iso: 'PW', name: '帛琉',           dial: '680' },
    { iso: 'FM', name: '密克羅尼西亞',   dial: '691' },
    { iso: 'MH', name: '馬紹爾群島',     dial: '692' },
    { iso: 'TV', name: '吐瓦魯',         dial: '688' },

    // 非洲
    { iso: 'EG', name: '埃及',       dial: '20'  },
    { iso: 'LY', name: '利比亞',     dial: '218' },
    { iso: 'TN', name: '突尼西亞',   dial: '216' },
    { iso: 'DZ', name: '阿爾及利亞', dial: '213' },
    { iso: 'MA', name: '摩洛哥',     dial: '212' },
    { iso: 'SD', name: '蘇丹',       dial: '249' },
    { iso: 'SS', name: '南蘇丹',     dial: '211' },
    { iso: 'ET', name: '衣索比亞',   dial: '251' },
    { iso: 'ER', name: '厄利垂亞',   dial: '291' },
    { iso: 'DJ', name: '吉布地',     dial: '253' },
    { iso: 'SO', name: '索馬利亞',   dial: '252' },
    { iso: 'KE', name: '肯亞',       dial: '254' },
    { iso: 'TZ', name: '坦尚尼亞',   dial: '255' },
    { iso: 'UG', name: '烏干達',     dial: '256' },
    { iso: 'RW', name: '盧安達',     dial: '250' },
    { iso: 'BI', name: '蒲隆地',     dial: '257' },
    { iso: 'CD', name: '剛果民主共和國', dial: '243' },
    { iso: 'CG', name: '剛果共和國', dial: '242' },
    { iso: 'GA', name: '加彭',       dial: '241' },
    { iso: 'CM', name: '喀麥隆',     dial: '237' },
    { iso: 'CF', name: '中非共和國', dial: '236' },
    { iso: 'TD', name: '查德',       dial: '235' },
    { iso: 'NG', name: '奈及利亞',   dial: '234' },
    { iso: 'NE', name: '尼日',       dial: '227' },
    { iso: 'BJ', name: '貝南',       dial: '229' },
    { iso: 'TG', name: '多哥',       dial: '228' },
    { iso: 'GH', name: '迦納',       dial: '233' },
    { iso: 'CI', name: '象牙海岸',   dial: '225' },
    { iso: 'LR', name: '賴比瑞亞',   dial: '231' },
    { iso: 'SL', name: '獅子山',     dial: '232' },
    { iso: 'GN', name: '幾內亞',     dial: '224' },
    { iso: 'GW', name: '幾內亞比索', dial: '245' },
    { iso: 'SN', name: '塞內加爾',   dial: '221' },
    { iso: 'GM', name: '甘比亞',     dial: '220' },
    { iso: 'ML', name: '馬利',       dial: '223' },
    { iso: 'BF', name: '布吉納法索', dial: '226' },
    { iso: 'MR', name: '茅利塔尼亞', dial: '222' },
    { iso: 'CV', name: '維德角',     dial: '238' },
    { iso: 'ZA', name: '南非',       dial: '27'  },
    { iso: 'NA', name: '納米比亞',   dial: '264' },
    { iso: 'BW', name: '波札那',     dial: '267' },
    { iso: 'ZW', name: '辛巴威',     dial: '263' },
    { iso: 'ZM', name: '尚比亞',     dial: '260' },
    { iso: 'MW', name: '馬拉威',     dial: '265' },
    { iso: 'MZ', name: '莫三比克',   dial: '258' },
    { iso: 'LS', name: '賴索托',     dial: '266' },
    { iso: 'SZ', name: '史瓦帝尼',   dial: '268' },
    { iso: 'MG', name: '馬達加斯加', dial: '261' },
    { iso: 'MU', name: '模里西斯',   dial: '230' },
    { iso: 'SC', name: '塞席爾',     dial: '248' },
    { iso: 'KM', name: '葛摩',       dial: '269' },
    { iso: 'AO', name: '安哥拉',     dial: '244' },
    { iso: 'ST', name: '聖多美普林西比', dial: '239' },

    // 美洲
    { iso: 'US', name: '美國',       dial: '1'    },
    { iso: 'CA', name: '加拿大',     dial: '1'    },
    { iso: 'MX', name: '墨西哥',     dial: '52'   },
    { iso: 'GT', name: '瓜地馬拉',   dial: '502'  },
    { iso: 'BZ', name: '貝里斯',     dial: '501'  },
    { iso: 'SV', name: '薩爾瓦多',   dial: '503'  },
    { iso: 'HN', name: '宏都拉斯',   dial: '504'  },
    { iso: 'NI', name: '尼加拉瓜',   dial: '505'  },
    { iso: 'CR', name: '哥斯大黎加', dial: '506'  },
    { iso: 'PA', name: '巴拿馬',     dial: '507'  },
    { iso: 'CU', name: '古巴',       dial: '53'   },
    { iso: 'JM', name: '牙買加',     dial: '1876' },
    { iso: 'HT', name: '海地',       dial: '509'  },
    { iso: 'DO', name: '多明尼加',   dial: '1809' },
    { iso: 'BS', name: '巴哈馬',     dial: '1242' },
    { iso: 'TT', name: '千里達及托巴哥', dial: '1868' },
    { iso: 'BB', name: '巴貝多',     dial: '1246' },
    { iso: 'CO', name: '哥倫比亞',   dial: '57'   },
    { iso: 'VE', name: '委內瑞拉',   dial: '58'   },
    { iso: 'GY', name: '蓋亞那',     dial: '592'  },
    { iso: 'SR', name: '蘇利南',     dial: '597'  },
    { iso: 'EC', name: '厄瓜多',     dial: '593'  },
    { iso: 'PE', name: '秘魯',       dial: '51'   },
    { iso: 'BR', name: '巴西',       dial: '55'   },
    { iso: 'BO', name: '玻利維亞',   dial: '591'  },
    { iso: 'PY', name: '巴拉圭',     dial: '595'  },
    { iso: 'CL', name: '智利',       dial: '56'   },
    { iso: 'AR', name: '阿根廷',     dial: '54'   },
    { iso: 'UY', name: '烏拉圭',     dial: '598'  },
    { iso: 'AG', name: '安地卡及巴布達', dial: '1268' },
    { iso: 'LC', name: '聖露西亞',   dial: '1758' },
    { iso: 'VC', name: '聖文森及格瑞那丁', dial: '1784' },
    { iso: 'GD', name: '格瑞那達',   dial: '1473' },
    { iso: 'DM', name: '多米尼克',   dial: '1767' },
    { iso: 'KN', name: '聖克里斯多福及尼維斯', dial: '1869' }
  ];

  REST.sort(function (a, b) {
    return a.name.localeCompare(b.name, 'zh-Hant-TW-u-co-stroke');
  });

  return PINNED.concat(REST);
})();
